function sol_ddq1 = compute_ddq1(q1,q2,q3,dq1,dq2,dq3,L1,L2,L3,m1,m2,m3,g)
%COMPUTE_DDQ1
%    SOL_DDQ1 = COMPUTE_DDQ1(Q1,Q2,Q3,DQ1,DQ2,DQ3,L1,L2,L3,M1,M2,M3,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    16-Nov-2024 02:55:41

t2 = sin(q1);
t3 = sin(q2);
t4 = dq1.^2;
t5 = dq2.^2;
t6 = m2.^2;
t7 = q2.*2.0;
t8 = q3.*2.0;
t12 = -q3;
t9 = cos(t7);
t10 = cos(t8);
t11 = sin(t7);
t13 = -t8;
t14 = q1+t7;
t15 = q1+t8;
t16 = q2+t8;
t21 = q2+t12;
t22 = t7+t8;
t17 = sin(t14);
t18 = sin(t15);
t19 = sin(t16);
t20 = q1+t13;
t24 = sin(t21);
t23 = sin(t20);
et1 = 1.0./(L1.*(t6.*2.0+m1.*m2+m1.*m3.*2.0+m2.*m3.*6.0-t6.*t9.*2.0+m2.*m3.*cos(t22).*2.0-m1.*m3.*t10.*2.0-m2.*m3.*t9.*4.0-m2.*m3.*t10.*4.0));
et2 = (-g.*t2.*t6+g.*t6.*t17+L2.*t3.*t4.*t6+L2.*t3.*t5.*t6+L1.*t4.*t6.*t11-g.*m1.*m2.*t2-g.*m1.*m3.*t2.*2.0-g.*m2.*m3.*t2.*3.0+g.*m1.*m3.*t18+g.*m2.*m3.*t17.*2.0+g.*m2.*m3.*t18+g.*m1.*m3.*t23+g.*m2.*m3.*t23-g.*m2.*m3.*sin(t8+t14)+L2.*dq1.*dq2.*t3.*t6.*2.0+L2.*m2.*m3.*t3.*t4.*3.0+L2.*m2.*m3.*t3.*t5.*3.0+L1.*m2.*m3.*t4.*t11.*2.0-L2.*m2.*m3.*t4.*t19-L2.*m2.*m3.*t5.*t19+L3.*m2.*m3.*t4.*t24+L3.*m2.*m3.*t5.*t24+L3.*dq3.^2.*m2.*m3.*t24-L1.*m2.*m3.*t4.*sin(t22)+L2.*dq1.*dq2.*m2.*m3.*t3.*6.0-L2.*dq1.*dq2.*m2.*m3.*t19.*2.0+L3.*dq1.*dq2.*m2.*m3.*t24.*2.0+L3.*dq1.*dq3.*m2.*m3.*t24.*2.0+L3.*dq2.*dq3.*m2.*m3.*t24.*2.0).*2.0;
sol_ddq1 = et1.*et2;
end
